---
- name: Configurations | Install Nuget package provider
  win_shell: |
    Install-PackageProvider -Name Nuget -Force

- name: Configurations | Install PSCX PS Module
  win_psmodule:
    name: Pscx
    accept_license: true
    allow_clobber: true
    state: present

- name: Configurations | Disable AMSI using powershell
  win_shell: |
    Set-MpPreference -DisableRealtimeMonitoring $true
    Set-MpPreference -DisableBehaviorMonitoring $true
    Set-MpPreference -DisableScriptScanning $true

- name: Configurations | Download required utilities
  win_get_url:
    url: "{{ item.link }}"
    dest: "{{ temp_space }}\\{{ item.name }}"
  loop:
    - { link: "https://www.sordum.org/files/downloads.php?st-windows-update-blocker", name: "windows-update-blocker.zip" }
    - { link: "https://www.sordum.org/files/downloads.php?st-edge-block", name: "edge-block.zip" }
    - { link: "https://www.sordum.org/files/downloads.php?st-net-disabler", name: "net-disabler.zip" }
    - { link: "https://github.com/r0ttenbeef/BlackMega-VM/releases/download/dControl/defender-control.zip", name: "defender-control.zip" }

- name: Configurations | Unzip downloaded utilities
  win_unzip:
    src: "{{ temp_space }}\\{{ item.archive }}"
    dest: "{{ temp_space }}"
    delete_archive: true
    password: blackmega
  loop:
    - { archive: "windows-update-blocker.zip" }
    - { archive: "edge-block.zip" }
    - { archive: "net-disabler.zip" }
    - { archive: "defender-control.zip" }

- name: Configurations | Moving the required files only to Maintainance
  win_copy:
    src: "{{ temp_space }}\\{{ item.file_path }}"
    dest: "{{ ansible_env.USERPROFILE }}\\Desktop\\My_Tools\\Maintainance\\{{ item.file_name }}"
    remote_src: true
  loop:
    - { file_path: "Wub\\Wub_x64.exe", file_name: "Windows Update Blocker.exe" }
    - { file_path: "EdgeBlock\\EdgeBlock_x64.exe", file_name: "Edge Block.exe" }
    - { file_path: "NetDisabler\\NetDisabler_x64.exe", file_name: "Net Disabler.exe" }
    - { file_path: "dControl.exe", file_name: "Defender Control.exe" }

- name: Configurations | Disable windows updates
  win_shell: |
   cmd /c '{{ ansible_env.USERPROFILE }}\Desktop\My_Tools\Maintainance\Windows Update Blocker.exe' /D /P

- name: windows Disable | Disable microsoft edge
  win_shell: |
    cmd /c '{{ ansible_env.USERPROFILE }}\Desktop\My_Tools\Maintainance\Edge Block.exe' /B

- name: Configurations | Show files extensions
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword
    state: present

- name: Configurations | Enable showing hidden files via registry
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: Hidden
    data: 1
    type: dword
    state: present

- name: Configurations | Enable showing protected operating system files via registry
  win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: ShowSuperHidden
    data: 1
    type: dword
    state: present

- name: Configurations | Revert back to the classic context menu on windows 11
  win_regedit:
    path: HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: ''
    state: present
