---
- name: Transcript | Enable powershell transcript logging via registry
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableTranscripting
    data: 1
    type: dword

- name: Transcript | Enable Invocation Header via registry
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableInvocationHeader
    data: 1
    type: dword

- name: Transcript | Set the output directory via registry
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\Transcription
    name: OutputDirectory
    data: "{{ ansible_env.USERPROFILE }}\\Desktop\\PS_Transcript Logs"
    type: string
